"""empty message

Revision ID: 5bbdfdf1e8ef
Revises: 
Create Date: 2017-09-15 15:14:55.696473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbdfdf1e8ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'category', 'category_match', ['categorymatchID'], ['categorymatchID'])
    op.create_foreign_key(None, 'job_matches', 'candidates', ['candidatesID'], ['candidatesID'])
    op.create_foreign_key(None, 'jobs', 'category_match', ['postCategoryID'], ['categorymatchID'])
    op.create_foreign_key(None, 'jobs', 'experience_level', ['ExperienceLevelID'], ['experienceLevelID'])
    op.create_foreign_key(None, 'jobs', 'company_type', ['companyTypeID'], ['companyTypeID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    # ### end Alembic commands ###
